source ~/.zsh/checks.zsh
source ~/.zsh/colors.zsh
source ~/.zsh/setopt.zsh
source ~/.zsh/exports.zsh
source ~/.zsh/prompt.zsh
source ~/.zsh/completion.zsh
source ~/.zsh/aliases.zsh
source ~/.zsh/bindkeys.zsh
source ~/.zsh/functions.zsh
source ~/.zsh/history.zsh
# source ~/.zsh/zsh_hooks.zsh
source ~/.zsh/oh-my-zsh.zsh

# added by travis gem
[ -f /Users/wjie/.travis/travis.sh ] && source /Users/wjie/.travis/travis.sh

