source ~/.zsh/checks.zsh
source ~/.zsh/colors.zsh
source ~/.zsh/setopt.zsh
source ~/.zsh/exports.zsh
source ~/.zsh/prompt.zsh
source ~/.zsh/completion.zsh
source ~/.zsh/aliases.zsh
source ~/.zsh/bindkeys.zsh
source ~/.zsh/functions.zsh
source ~/.zsh/history.zsh
# source ~/.zsh/zsh_hooks.zsh
source ~/.zsh/oh-my-zsh.zsh

# added by travis gem
[ -f ~/.travis/travis.sh ] && source ~/.travis/travis.sh


# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/wenbo/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/wenbo/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/wenbo/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/wenbo/google-cloud-sdk/completion.zsh.inc'; fi

export NVM_DIR="$HOME/.nvm"
. "/usr/local/opt/nvm/nvm.sh"
